require("core.plugin_config.gruvbox")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.lualine")
require("core.plugin_config.telescope")
require("core.plugin_config.nvim-cmp")
require("core.plugin_config.lsp.mason")
require("core.plugin_config.lsp.lspconfig")
require("core.plugin_config.lsp.lspsaga")
